### ISSUE TITLE
Maximizing vibration data sampling rate from ADXL357 for condition monitoring application

### ISSUE THREAD

**Issue by parminder4499** [Seeed-Studio/Seeed_Sketch_ADXL356X#1]
Hi there !!

I am building a vibration monitoring application using ADXL357 with esp32 microcontroller. As per the information provided in cbm setup guide by ADI the number of datapoints collected in a second should be 5khz for 2.4 khz bandwidth. 

I have set the ODR_LPF at 2000 Hz and 500 Hz and HPF_CORNER at 6.2084 × 10−4 × ODR. and esp32 baud rate at 115200 through I2C. 

Problem:

I am getting 350 - 410 samples of vibration data in a second when I run a count to calculate the no of samples/sec. 

Question 

How can I get 5000 data samples/ sec ? 

Is my way of measuring the sampling data rate using a counter correct?

Kindly provide me some guidance in the right direction. 

Thanks.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
